// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq94l-t2CM2PPpnVkOmXk4I--hqYJ4jzo',
    appId: '1:695630192491:web:eeec3d3e30b183e42e362e',
    messagingSenderId: '695630192491',
    projectId: 'bmicalculator-80265',
    authDomain: 'bmicalculator-80265.firebaseapp.com',
    storageBucket: 'bmicalculator-80265.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJbNQvgknel7FVkTa9fsaklO37P4SJtsU',
    appId: '1:695630192491:android:4941c5ba3427da302e362e',
    messagingSenderId: '695630192491',
    projectId: 'bmicalculator-80265',
    storageBucket: 'bmicalculator-80265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-v2BVsvlzShk-xNxkpTGKtsjp93YGbNo',
    appId: '1:695630192491:ios:105c960043ce63d12e362e',
    messagingSenderId: '695630192491',
    projectId: 'bmicalculator-80265',
    storageBucket: 'bmicalculator-80265.firebasestorage.app',
    iosBundleId: 'com.example.digitalKhata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-v2BVsvlzShk-xNxkpTGKtsjp93YGbNo',
    appId: '1:695630192491:ios:105c960043ce63d12e362e',
    messagingSenderId: '695630192491',
    projectId: 'bmicalculator-80265',
    storageBucket: 'bmicalculator-80265.firebasestorage.app',
    iosBundleId: 'com.example.digitalKhata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq94l-t2CM2PPpnVkOmXk4I--hqYJ4jzo',
    appId: '1:695630192491:web:9393912444f2c9452e362e',
    messagingSenderId: '695630192491',
    projectId: 'bmicalculator-80265',
    authDomain: 'bmicalculator-80265.firebaseapp.com',
    storageBucket: 'bmicalculator-80265.firebasestorage.app',
  );
}
